#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: FireTV
# Runs the FireTV Server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh


hass.log.info 'Starting the FireTV Server'

# Run the FireTV Server
exec firetv-server -c /config/aftv.yaml